{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Filesystem Size (Gib)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/root\"} / 1_000_000_000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device=\"/dev/root\"} - node_filesystem_avail_bytes{device=\"/dev/root\"}) / node_filesystem_size_bytes{device=\"/dev/root\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saved Ipfs Hashes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "ipfs_hashes", "legendFormat": "__auto" }
   ]
  }
 ]
}