[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
DOCKER_BUILDER_IMAGE = "builder:latest"

[tasks.start-colima]
script = '''
colima start
'''

[tasks.docker-build-builder]
env = { "RUST_VERSION" = "1.81.0" }
script = '''
docker build . -f docker/images/builder.Dockerfile \
     --build-arg RUST_VERSION=$RUST_VERSION \
    -t $DOCKER_BUILDER_IMAGE
'''

[tasks.docker-build]
script = '''
COMPONENT=${@}
docker build .  \
    --build-arg BUILDER_IMAGE=$DOCKER_BUILDER_IMAGE \
    -f docker/images/$COMPONENT.Dockerfile \
    -t $COMPONENT:latest
'''