[package]
name = "cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
jsonrpsee = { workspace = true , features = ["client"] }
openssl = { workspace = true, features = ["vendored"]  }
server = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
