services:
  ipfs:
    container_name: ipfs
    image: ipfs/kubo:v0.33.2
    environment:
      IPFS_PATH: /data/ipfs
    volumes:
      - ./../data/ipfs:/data/ipfs
    ports:
      - 4001:4001
      - 4002:4002/udp
      - 4003:4003
      - 5001:5001
      - 8080:8080
  rpc:
    container_name: rpc
    command: |
      server start-server --port ${PORT}
    image: server:latest
    ports:
      - ${PORT}:${PORT}
