services:
  ipfs:
    container_name: ipfs
    image: ipfs/kubo:v0.33.2
    environment:
      IPFS_PATH: /data/ipfs
      IPFS_LOGGING: 'debug'
      IPFS_LOGGING_LEVEL: debug
    volumes:
      - ./../data/ipfs:/data/ipfs
    ports:
      - 4001:4001
      - 4002:4002/udp
      - 4003:4003
      - 5001:5001
      - 8080:8080
