services:
  ipfs:
    container_name: ipfs
    image: ipfs/kubo:v0.33.2
    environment:
      IPFS_PATH: /data/ipfs
    volumes:
      - ipfs:/data/ipfs
    ports:
      - 4001:4001
      - 4002:4002/udp
      - 4003:4003
      - 5001:5001
      - 8080:8080

  rpc:
    container_name: rpc
    command: |
      server start-server --port 8008 --enable-metrics
    image: server:latest
    environment:
      IPFS_BASE_URL: http://ipfs:5001
      PUSH_GATEWAY_BASE_URL: http://push-gateway:9091
    ports:
      - 8008:8008

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
     - '9100:9100'

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
     - '9090:9090'

  push-gateway:
    image: prom/pushgateway:v1.11.1 
    container_name: push-gateway
    restart: unless-stopped
    ports:
     - '9091:9091'

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    ports:
     - '3000:3000'
    volumes:
      - ./configs/grafana-prometheus-datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - 'grafana_storage:/var/lib/grafana'

volumes:
  grafana_storage: {}
  prometheus_data: {}
  ipfs: {}